#cloud-config
ssh_authorized_keys:
  - ssh-rsa 
rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.1.20
        gateway: 192.168.1.1
        dhcp: false
        mtu: 1500
    dns:
      nameservers:
        - 192.168.1.2
        - 8.8.8.8
  hostname: ROS01
